### ISSUE TITLE
delete an improper individual

### ISSUE THREAD

**Issue by wj314** [schlatterbeck/pgapack#6]
Hi,
      When I carried out evaluate function in PGAEvaluate, I found some individuals are so improper that I reproduce these individuals by PGARealInitString but evaluation still failed:

double evaluate(PGAContext *ctx, int p, int pop, double *aux)
{
    int lenp=PGAGetStringLength (ctx);
    double e=0;
    int index=PGAGetIndividual(ctx, p, pop)->index;
    int rank;
    rank=PGAGetRank (ctx, MPI_COMM_WORLD);
    for (int i=0;i<lenp;i++)
    {
        double pv=PGAGetRealAllele (ctx, p, pop, i);
        gachangereaxc(i+1,pv);
    }
    string fffile="ffield.run."+to_string(index);
    reaxc.writereaxff(fffile);

    // calculate ffield value of trainset data ; if lammps return error, reproduce an individual and calculate again

    int calcagain=0;
    int calccycle=0;
    while(true)
    {
        try
        {
            calcgeo(comm,index,fffile);

            calcagain=0;
        }
        catch(...)
        {
            calcagain=1;
        }
        calccycle++;
        if (calcagain==0)
        {
            break;
        }
        else
        {
            if (calccycle<=control.cycleofexception)
            {
                printf("calcgeo error start re %d  p= %d \n",calccycle,index);
                if (control.reobtain==1)
                {
                    PGARealMutation(ctx,  p,  pop, control.exceptionmutprob);
                }
                else if (control.reobtain==2)
                {
                    PGARealInitString ( ctx,  p,  pop);
                }

                for (int i=0;i<lenp;i++)
                {
                    double pv=PGAGetRealAllele (ctx, p, pop, i);
                    gachangereaxc(i+1,pv);
                }
                reaxc.writereaxff(fffile);
                continue;
            }
            else
            {
                printf("Error: calcgeo failed count exceeds cycleofexception %d in Rank %d \n",control.cycleofexception,rank);
                MPI_Abort(MPI_COMM_WORLD,1);
            }
        }

    }
    double totalerror=calcerror("trainset.error."+to_string(index));

    return totalerror;

}

So can I return a large error in evaluate function, explicitly abandon the individuals and make sure they don't enter the next generation?

**Comment by schlatterbeck** [comment]
Yes I guess if you have very bad individuals your evaluation function should reflect just that by giving back a very bad evaluation.

Note that If you're running a parallel version of pgapack, changing the individual in the evaluation function will *not* change that individual in the rank-0 (master) process. It will only be a local change that is thrown away afterwards. A further reason to keep the evaluation function as simple as possible.

**Comment by wj314** [comment]
Thanks for your reply. 

So your advice is that I only give back a very bad evaluation and do not reproduce a new individual in my evaluation function?

**Comment by schlatterbeck** [comment]
On Fri, Nov 11, 2022 at 12:35:06AM -0800, wj314 wrote:
> 
> So your advice is that I only give back a very bad evaluation and do
> not reproduce a new individual in my evaluation function?

Yes, exactly. In a distributed (MPI) version you cannot change an
individual during evaluation because it is transmitted from the rank-0
process to another process for evaluation but never transmitted back.
Only the evaluation is transmitted back to the rank-0 process.

Ralf
-- 
Dr. Ralf Schlatterbeck                  Tel:   +43/2243/26465-16
Open Source Consulting                  www:   www.runtux.com
Reichergasse 131, A-3411 Weidling       email: ***@***.***

**Comment by wj314** [comment]
One of the stopping rules is that no change in the best solution found in a given number of iterations.
Here, does "no change" mean that the difference between old best evaluation and new best evaluation is 0?
Can I give a certain value instead of 0?

**Comment by schlatterbeck** [comment]
On Fri, Nov 11, 2022 at 01:20:14AM -0800, wj314 wrote:
> One of the stopping rules is that no change in the best solution found
> in a given number of iterations.
> Here, does "no change" mean that the difference between old best
> evaluation and new best evaluation is 0?

Yes, but only for the *best* evaluation. So if the best evaluation does
not change for a number of evaluations the algorithm stops.

> Can I give a certain value instead of 0?

No, but it is possible to define your own stopping function something
like this:

PGASetUserFunction (ctx, PGA_USERFUNCTION_STOPCOND, My_StopCond);

int My_StopCond (PGAContext *ctx) {
    if (FIXME: Your check goes here) {
        return PGA_TRUE;
    }
    return PGACheckStoppingConditions (ctx);
}

This allows you to add an additional check when the algorithm should
stop. If you want to *replace* the existing checks you would simply
return PGA_FALSE instead of the call to PGACheckStoppingConditions.
But it's usually a good idea to keep the existing stop-checks,
especially an upper bound on the number of generations.

Ralf
-- 
Dr. Ralf Schlatterbeck                  Tel:   +43/2243/26465-16
Open Source Consulting                  www:   www.runtux.com
Reichergasse 131, A-3411 Weidling       email: ***@***.***
